# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty
paginate:            5
gems:                [jekyll-paginate]

# Setup
title:               Words & Things
tagline:             'A somewhat coherant webblog'
description:         ''
url:                 http://josephmclaughl.in
baseurl:             ''

# About/contact
author:
  name:              Joseph McLaughlin
  url:               https://twitter.com/mclaughj
  email:             me@josephmclaughl.in

# Custom vars
version:             1.0.0
