# Site settings
title: Zero1 Software
tag_text: Zero1 Software
description: Zero1 Software is a one-man software development shop.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
