# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Joseph McLaughlin
tagline:             'Some thoughts.'
description:         ''
url:                 http://josephmclaughl.in
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joseph McLaughlin
  url:               https://twitter.com/mclaughj
  email:             me@josephmclaughl.in

# Custom vars
version:             1.0.0
